#include <glib.h>
// For printf, will (probably) go away with a test framework
#include <stdio.h>
#include <stdbool.h>
// Tested function
#include "midi/helpers.h"
// Random number generation
#include <time.h>
#include <stdlib.h>

int main() {
    // A variable holding last generated byte we add to GArray
    unsigned char generated_bytearray_byte;
    unsigned char last_bytearray_byte;

    // Init random number generator
    srand(time(NULL));

    // An empty GArray of bytes
    GArray * bytes = g_array_sized_new(FALSE, FALSE, sizeof(unsigned char), 0);

    unsigned int stop_at = 1 + rand() % 99;
    for (unsigned int i = 0; i < stop_at; i++) {
        generated_bytearray_byte = rand() % 99;
    }

    // Append the last generated byte
    g_array_append_val(bytes, generated_bytearray_byte);

    // Retrieve the last byte
    last_bytearray_byte = get_last_bytearray_byte(bytes);

    printf("Last generated: %d\n", generated_bytearray_byte);
    printf("Last bytearray element: %d\n", last_bytearray_byte);
    printf("Equality: %d\n", generated_bytearray_byte == last_bytearray_byte);

    g_array_free(bytes, true);

    // Exit without an error
    return 0;
}
